/*INSERTS CATEGORIA*/
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (1,"erat vel pede blandit congue. In scelerisque scelerisque dui.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (2,"montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (3,"neque. Sed eget lacus. Mauris non dui nec urna suscipit","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (4,"Aenean gravida nunc sed pede.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (5,"vel, convallis in,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (6,"turpis. Nulla aliquet. Proin velit.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (7,"in, tempus eu, ligula. Aenean euismod mauris eu elit.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (8,"quis, pede. Suspendisse dui. Fusce diam nunc,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (9,"eu, odio. Phasellus at augue id ante dictum cursus. Nunc","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (10,"eu nibh vulputate mauris sagittis placerat.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (11,"lobortis augue scelerisque","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (12,"dis parturient montes, nascetur ridiculus mus.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (13,"semper erat, in consectetuer ipsum nunc id enim.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (14,"a purus. Duis elementum, dui","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (15,"ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (16,"Nullam feugiat placerat velit. Quisque varius. Nam","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (17,"in sodales elit erat","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (18,"convallis in, cursus et, eros. Proin ultrices.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (19,"magna nec","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (20,"malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (21,"rhoncus.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (22,"non justo. Proin non massa non ante bibendum","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (23,"nec luctus felis purus ac tellus. Suspendisse sed dolor.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (24,"Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (25,"Phasellus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (26,"sociis natoque penatibus et magnis dis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (27,"lectus sit","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (28,"mauris sapien, cursus in, hendrerit consectetuer, cursus et,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (29,"sed, facilisis vitae, orci. Phasellus dapibus quam quis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (30,"consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (31,"nec tempus scelerisque, lorem ipsum sodales","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (32,"justo. Praesent luctus. Curabitur egestas nunc","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (33,"elementum at, egestas","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (34,"sit","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (35,"placerat. Cras dictum ultricies ligula. Nullam enim. Sed","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (36,"euismod mauris eu elit.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (37,"ipsum primis in faucibus orci luctus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (38,"sem ut cursus luctus, ipsum leo elementum sem, vitae","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (39,"odio a purus. Duis elementum, dui quis accumsan convallis,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (40,"Morbi accumsan laoreet ipsum.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (41,"sem, vitae","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (42,"orci lacus vestibulum lorem, sit amet ultricies sem magna","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (43,"in, cursus et, eros. Proin ultrices. Duis volutpat nunc","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (44,"magna tellus faucibus leo, in","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (45,"Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (46,"rutrum urna, nec luctus felis purus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (47,"vitae, erat. Vivamus nisi. Mauris nulla. Integer urna.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (48,"nulla. Cras eu","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (49,"iaculis enim, sit amet ornare lectus justo","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (50,"sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (51,"natoque","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (52,"natoque penatibus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (53,"tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (54,"sit amet, consectetuer adipiscing elit. Etiam laoreet,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (55,"fermentum metus. Aenean","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (56,"enim diam vel arcu. Curabitur ut","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (57,"ac tellus.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (58,"lobortis risus. In mi pede, nonummy ut, molestie","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (59,"pede et risus. Quisque libero lacus,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (60,"non, lobortis quis, pede. Suspendisse dui.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (61,"in molestie tortor nibh sit amet orci. Ut sagittis lobortis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (62,"lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (63,"aliquet, sem ut cursus luctus, ipsum","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (64,"est arcu ac orci. Ut semper pretium","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (65,"ultrices, mauris ipsum","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (66,"faucibus orci luctus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (67,"enim consequat purus. Maecenas libero","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (68,"orci, consectetuer euismod est","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (69,"sit amet nulla. Donec non justo. Proin non massa non","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (70,"Vestibulum ante ipsum primis in faucibus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (71,"convallis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (72,"turpis","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (73,"ipsum. Suspendisse sagittis. Nullam vitae diam.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (74,"Nullam velit dui, semper et, lacinia vitae, sodales","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (75,"Sed congue, elit sed consequat auctor, nunc nulla vulputate","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (76,"et nunc. Quisque ornare","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (77,"In faucibus. Morbi vehicula. Pellentesque","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (78,"Nunc quis arcu vel quam dignissim pharetra. Nam ac","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (79,"commodo auctor velit. Aliquam","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (80,"est, mollis non, cursus non, egestas a, dui. Cras pellentesque.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (81,"at, velit.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (82,"tellus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (83,"sit amet ante. Vivamus non lorem vitae odio sagittis semper.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (84,"imperdiet nec, leo.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (85,"magna tellus faucibus leo, in lobortis tellus justo","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (86,"molestie dapibus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (87,"enim. Sed nulla","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (88,"urna justo faucibus lectus, a sollicitudin","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (89,"arcu. Sed et libero. Proin mi. Aliquam","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (90,"Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (91,"Quisque porttitor eros","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (92,"eleifend","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (93,"primis in faucibus orci","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (94,"eu","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (95,"lectus","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (96,"nunc sed pede. Cum sociis natoque","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (97,"amet risus. Donec egestas. Aliquam nec enim.","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (98,"lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (99,"sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam","1");
INSERT INTO `tb_Categoria` (`id`,`descricao`,`version`) VALUES (100,"accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus","1");

/*INSERTS CLIENTE*/
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (35444258805,"18-10-28","17-10-02","nec@fringillaporttitorvulputate.net",1,"Kylan","Ethan Gaines","Standart","XUX06ELI4KX","(06)4170-3286","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (13748242845,"17-07-16","19-02-22","In.faucibus@lectusa.com",2,"Karen","Colorado Vaughan","Standart","KNO73DHC7HE","(85)3893-5729","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (6903184065,"19-03-07","18-11-20","ante.ipsum@nullaDonecnon.net",3,"Jerome","Jasmine Leon","Standart","ZGM94QSN0NV","(86)0401-8829","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (59777218755,"18-07-10","18-09-26","luctus.ut@montes.ca",4,"Arthur","Neville Harrell","Standart","ZYJ42SUF5PN","(72)5248-8251","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (68502338137,"17-07-21","19-03-28","vel.mauris.Integer@Fusce.edu",5,"Willar","Cooper Graves","Standart","HFU18MEN3ED","(99)0761-5103","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (53439408307,"18-01-24","17-07-30","amet.consectetuer.adipiscing@in.co.uk",6,"Gil","Lesley Horne","Standart","SVB84RUQ5ME","(54)8728-0040","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (94308419292,"17-07-24","19-02-15","rhoncus@vitaemauris.ca",7,"April","Audrey Murray","Standart","IMT22GFF5MW","(29)3990-9726","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (37824210897,"18-06-28","18-06-13","Mauris.vel@anteipsum.com",8,"Stuart","Dahlia Hardin","Standart","WRM53DOH1XV","(28)3084-7198","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (47303185425,"17-09-23","18-07-21","posuere.at.velit@erat.co.uk",9,"Mason","Anthony Brock","Standart","BPE59UMI1OA","(53)7775-5160","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (98459644708,"18-04-18","17-08-31","imperdiet.dictum@ultriciessemmagna.ca",10,"Carolyn","Dillon Strickland","Standart","PDW00DEF3TR","(67)8125-0507","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (19718935061,"18-12-19","18-12-15","nisl@sagittis.com",11,"Russell","Mohammad Kirby","Standart","UPZ81MEA8HR","(67)9328-3850","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (84225955000,"19-02-12","17-10-21","Pellentesque@malesuadafringilla.org",12,"Davis","Elton Cantu","Standart","SLJ10LPV5PI","(31)2536-5855","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (16869466798,"18-09-19","17-08-12","nec.tellus@ipsumnon.net",13,"Tanek","Moses Chan","Standart","GNR96PPE8SR","(71)8165-6335","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (57035371148,"17-09-16","19-05-13","enim.Mauris@auctor.org",14,"Justine","Lillian Henry","Standart","BBG48DXQ0MC","(92)4408-3168","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (875765644,"18-10-16","18-08-31","consequat.nec@tincidunt.com",15,"Quinilan","Caesar Hendricks","Standart","SLA79FNS2EG","(65)7264-5300","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (91336100874,"18-04-09","19-03-19","Mauris.quis.turpis@ornarelectusante.edu",16,"Jordan","Morgan Rosario","Standart","DFV61GJT2DL","(93)0445-4455","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (43979508103,"18-10-12","18-12-21","quam.Curabitur@viverraMaecenasiaculis.co.uk",17,"Xander","Amena Arnold","Standart","UBY69UCH5BL","(27)0157-5222","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (22638395335,"18-01-02","17-07-13","enim.non.nisi@egestasSedpharetra.co.uk",18,"Gemma","Mia Garza","Standart","GSG15TUQ1NR","(36)1911-9614","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (80514241196,"17-09-14","18-04-20","pellentesque.tellus@Nunclectus.ca",19,"Lareina","Breanna Stuart","Standart","PHJ04MHC3KJ","(13)8150-7578","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (82741766562,"17-08-10","18-12-22","auctor.nunc.nulla@in.org",20,"Cruz","Robin Daniels","Standart","JAB67TVQ3ZF","(18)1737-1907","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (12097658263,"18-08-15","18-07-06","Fusce@sitamet.com",21,"Madaline","Alexa Craig","Standart","PCK27OCR0XJ","(91)5460-1983","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (39690341288,"19-01-29","18-12-14","vitae.sodales@sit.co.uk",22,"Ila","Kiayada Munoz","Standart","JYF97FKK3AC","(64)9859-1830","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (53779490943,"18-11-21","18-01-18","facilisi.Sed.neque@ridiculus.com",23,"Wyatt","Ishmael Ross","Standart","NNM42TXE3VA","(97)5863-4391","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (4925691243,"18-10-31","18-11-17","dapibus.id.blandit@in.ca",24,"Graiden","Chaim Knight","Standart","AEC14ELM0EX","(16)5249-1174","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (35490904282,"17-05-30","19-04-12","fringilla@acmi.ca",25,"Joshua","Glenna Craig","Standart","VXJ05TFY2CD","(30)7581-6228","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (13409640220,"18-11-29","17-06-20","ipsum@mauris.co.uk",26,"Christian","Eric Joyce","Standart","OSP63BHR7IJ","(68)9699-9347","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (74838731484,"17-08-15","18-03-18","et.ipsum@sociis.ca",27,"Faith","Colin Richmond","Standart","VZT77CQM0AZ","(76)7177-8786","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (75116422120,"19-02-01","19-02-18","dapibus@at.edu",28,"Blaze","Trevor Watts","Standart","SAG75WJW0CR","(15)7023-4297","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (60723981773,"18-10-12","18-06-13","lacinia@inhendrerit.co.uk",29,"Kibo","Iliana Cleveland","Standart","LOT00IXQ1PM","(13)6505-4922","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (76423477148,"19-02-19","17-08-27","parturient@euismodenimEtiam.net",30,"Melodie","Vanna Tillman","Standart","JNA63CWD5AS","(14)8996-5758","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (62165017286,"19-03-18","19-01-10","sed.dui@pedeultricesa.edu",31,"Melanie","Jared Bolton","Standart","SSJ09KJQ0MS","(03)1759-2726","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (58566583180,"19-01-11","18-03-17","eros.Proin.ultrices@vitaeodiosagittis.edu",32,"Taylor","Elliott Hickman","Standart","INU40FXI1KD","(15)6934-8398","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (71681679552,"18-11-06","17-12-20","elit.a@mollisPhasellus.org",33,"Alma","Isaiah Coleman","Standart","RFD30AJW5KK","(88)2669-3452","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (32215796783,"18-05-05","18-07-09","pede.Suspendisse.dui@nisi.org",34,"Evangeline","Joshua Miller","Standart","ECZ20KQJ5IR","(10)9534-8473","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (22843308094,"17-07-19","17-12-20","orci.quis.lectus@semelitpharetra.co.uk",35,"Bert","Brynne Chambers","Standart","KRI22EXT7AH","(98)3034-9039","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (42340071592,"17-08-11","18-03-04","Morbi.sit@Uttinciduntvehicula.net",36,"Xantha","Joel Cross","Standart","JJJ25OWH2GF","(44)7248-9799","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (14983419375,"17-07-24","18-09-23","amet@Sed.edu",37,"Buckminster","Gay Preston","Standart","FQE98TTG7FV","(48)2733-0818","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (44788487581,"18-11-18","18-07-18","non.magna.Nam@Donec.ca",38,"Josephine","Rose Benson","Standart","EQP88PCY8GS","(64)1160-8412","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (24236297700,"18-05-21","17-09-08","amet.consectetuer@non.org",39,"Nissim","Jeanette Vincent","Standart","RFS12CUO7YH","(85)3918-6870","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (62365925172,"18-07-24","18-11-02","nulla.Donec.non@semPellentesque.co.uk",40,"Belle","Benjamin Larson","Standart","GLL27OUY4WS","(83)8735-7436","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (62744792364,"17-07-23","18-09-12","magna@tempor.net",41,"Wynter","Brent Estes","Standart","QMU05PDA0SH","(51)2437-2048","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (84175803884,"18-03-04","18-01-18","Phasellus@velit.edu",42,"Henry","Hayley Huff","Standart","OOO75DJI6ZL","(54)4461-4472","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (49470851756,"17-11-30","18-04-01","risus.Nulla.eget@orciDonecnibh.org",43,"Elmo","Risa Lee","Standart","IJU99XWS6YC","(95)3687-3521","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (19360393891,"18-07-24","17-12-07","neque.tellus@dapibus.com",44,"Hillary","Camilla Jones","Standart","FVP93XUS2TA","(29)9260-1180","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (42438239278,"17-07-23","17-10-04","ornare@auguemalesuada.org",45,"Lydia","Nathaniel Gilliam","Standart","LVA78XXI4FP","(60)3814-3604","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (91839558258,"18-01-14","17-11-13","lacus.pede@idenim.com",46,"Ferris","Cheyenne Hayes","Standart","XVJ29DFE9JT","(90)0366-0458","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (35691564483,"17-10-26","17-12-09","tortor.at@etmagnis.net",47,"Deanna","Camille Sloan","Standart","CJJ92BSL0WN","(30)9528-1350","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (27825702121,"19-03-19","18-08-10","eu.ligula@euultricessit.com",48,"Francesca","Edward Deleon","Standart","QAW54NLY2UK","(65)7982-7442","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (58557672519,"17-12-08","18-05-25","Aliquam@laoreetposuereenim.net",49,"Talon","Debra Cline","Standart","JDG78AVQ8NJ","(68)2950-5629","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (36336474306,"18-09-10","18-06-06","ultrices@magnisdisparturient.ca",50,"Katell","Rae Mendoza","Standart","UAW42GKF7QU","(41)6803-0834","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (42892400175,"17-06-26","18-12-29","consequat.purus.Maecenas@vehiculaaliquet.ca",51,"Shelly","Zenaida Snow","Standart","UKY08NMU9KQ","(19)8711-8756","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (36196578620,"17-12-07","17-10-15","sodales.nisi.magna@Curabiturdictum.edu",52,"Joelle","Ocean Combs","Standart","JGE26GML8SC","(87)6931-3848","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (59234231524,"17-11-14","19-04-02","lectus.pede.et@quisdiamPellentesque.co.uk",53,"Colt","Carla Carlson","Standart","AUG65HQF3ST","(42)4237-1027","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (50004711933,"18-11-30","17-12-05","enim.Etiam.gravida@milacinia.org",54,"Ayanna","Jane Levine","Standart","MIZ97ETG7QM","(24)4874-8527","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (85131266899,"18-04-11","18-04-12","ridiculus.mus@ProinvelitSed.edu",55,"Jolie","Imelda Dale","Standart","RJX81YBL6JT","(85)3807-1142","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (21206257957,"19-01-06","19-02-01","mollis@sed.ca",56,"Jaquelyn","Dara Watson","Standart","BAV10WGC0YE","(96)4169-0304","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (53494124161,"17-09-09","18-01-05","metus.vitae@seddictum.net",57,"Akeem","Hilel Rosa","Standart","PNF06LAQ5WW","(88)1484-0001","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (74758706241,"18-04-13","17-11-25","quis.pede.Praesent@natoque.co.uk",58,"Darrel","Shelby Gould","Standart","WBY81KNF5JN","(73)1858-1054","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (99326517106,"18-12-28","19-05-06","arcu.ac@non.com",59,"Noble","Bradley Ramos","Standart","WXH53PST6BH","(21)2262-3852","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (88633796619,"18-04-09","18-08-14","Suspendisse@duinecurna.com",60,"Jena","Elton Valenzuela","Standart","ZVW62PUF9YO","(96)2922-6205","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (52167705912,"19-02-10","18-09-18","cursus.non@faucibusorciluctus.com",61,"Rachel","Merrill Keller","Standart","YFH04PJG3OV","(22)2453-2607","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (25830128369,"18-08-12","17-08-01","ultrices.a@necorciDonec.org",62,"Cedric","Chelsea Wiggins","Standart","KZL25NFT6TG","(54)9856-6662","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (35770334536,"17-11-20","17-08-30","lorem@nonsollicitudina.ca",63,"Cheryl","Charity Navarro","Standart","QMQ52VSF7LB","(72)7128-0163","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (59514252422,"18-12-03","18-12-01","semper@vestibulumneceuismod.com",64,"Cadman","Dominique Burch","Standart","CTT56CAO6DF","(88)5630-7865","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (44812191603,"18-06-05","18-06-11","enim.mi@velit.com",65,"Adele","Alvin Peters","Standart","TRL27SKN9HF","(52)2708-3760","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (30176867358,"18-03-28","17-09-10","convallis@erat.net",66,"Lev","Gabriel Copeland","Standart","TGY14NRH4SO","(50)2699-4569","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (74274856271,"18-10-16","17-12-12","pede.ac@antedictum.ca",67,"Caesar","Alea Miranda","Standart","WBU72ZEV2EV","(15)7632-8127","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (5098686600,"18-07-01","18-01-20","nisl.arcu@utipsumac.co.uk",68,"Quinlan","Micah Finch","Standart","GLE31DWJ8ZY","(30)3647-7660","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (34238289808,"18-01-02","18-12-05","ultrices@lobortis.org",69,"Rylee","Akeem Burke","Standart","ZWG49QIB9BG","(29)6202-5203","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (82378877187,"18-04-26","17-07-09","pharetra@sed.net",70,"Kylie","Rogan Gallegos","Standart","ZNB00VKP3XS","(23)7889-6789","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (88373216148,"17-08-16","18-09-20","cursus.et.eros@eliterat.edu",71,"Erin","Fay Oneal","Standart","LQA37AZB9ZX","(09)6650-6427","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (63823770731,"17-08-09","19-05-15","fermentum.vel.mauris@Duisvolutpatnunc.ca",72,"Oscar","Gretchen Watts","Standart","PPM04RTD5QE","(66)0454-3192","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (65855211718,"18-01-06","19-01-02","id.libero@Nullamscelerisque.com",73,"Mark","Hamish Roach","Standart","LVT83IXM4WZ","(02)0662-3835","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (61538483574,"19-03-02","17-06-05","dis.parturient@ultrices.com",74,"Levi","Uriel Price","Standart","DOY49WJU9YC","(59)0184-7708","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (71193284867,"18-03-25","18-02-28","pharetra.felis.eget@Morbi.org",75,"Todd","Brody Wilkerson","Standart","ERU40ADI9SP","(80)2224-9773","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (19725538091,"18-01-12","18-03-03","molestie.tellus.Aenean@consequatauctor.ca",76,"Robin","Clarke Aguirre","Standart","WPW85WSE2VJ","(49)4096-6973","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (65885354392,"18-12-12","18-01-18","faucibus.Morbi.vehicula@nonmassanon.co.uk",77,"Francis","Justine Greer","Standart","VTK48CPJ6EX","(57)3810-9870","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (77303204638,"19-05-03","18-11-26","dignissim@Vestibulum.ca",78,"Hayfa","Amity Harmon","Standart","ZDG33ESF7HX","(52)1145-1530","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (97928261384,"18-03-01","18-07-05","risus@Quisquelibero.ca",79,"Odette","Lev Lane","Standart","TVN51RTB3EY","(02)6856-7951","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (85673467349,"18-02-12","19-01-31","nec@nonummy.ca",80,"Patrick","Scott Reeves","Standart","KBS69ZBJ1BL","(33)0781-4855","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (56674729520,"18-04-08","17-10-23","tincidunt.pede@euenim.com",81,"Samantha","Kadeem Rutledge","Standart","VOU09ACO3NH","(19)9047-3325","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (85124012921,"18-05-18","17-05-29","Proin.non.massa@ipsum.edu",82,"Hector","Valentine Noble","Standart","QPX12KME8BJ","(87)5157-9950","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (56097955210,"18-01-30","18-12-28","sit@Pellentesquehabitant.org",83,"Lacota","Kathleen Barr","Standart","DVB58III9DP","(36)2562-0331","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (5348948156,"18-09-01","18-03-16","lacus.Nulla.tincidunt@sed.org",84,"Amena","Denton Sykes","Standart","VZC60AAE6QP","(07)3111-1281","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (8537698304,"17-10-11","19-05-02","Vivamus.rhoncus.Donec@quispedePraesent.ca",85,"Ulysses","Carlos Norman","Standart","ZWR05OMX0LC","(53)4982-5319","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (55929260980,"18-08-06","17-06-22","id@sapienimperdiet.org",86,"Willa","Scarlet Crawford","Standart","FMS16FOV2PW","(41)7116-8818","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (94091563764,"18-08-27","17-07-27","per@Quisqueporttitor.net",87,"Richard","Alexandra Benson","Standart","UDZ16EAJ4WJ","(87)6555-5608","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (76248607598,"17-08-02","18-05-07","montes.nascetur.ridiculus@convallisantelectus.net",88,"Kaye","Lee Tate","Standart","EYV61JNM0UZ","(69)0347-2613","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (96535244164,"19-02-28","17-07-26","risus.varius@estNunclaoreet.org",89,"Steel","Forrest Benson","Standart","UHV12AOL4YH","(06)9318-0736","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (4086492117,"17-10-13","19-03-02","non.egestas@Namporttitorscelerisque.org",90,"Hiram","Robin Burns","Standart","YIN37NUV9FJ","(58)4289-1278","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (81392014818,"18-07-21","18-07-09","amet.metus@vel.co.uk",91,"Justin","Jordan Jordan","Standart","HGU51EDJ4CH","(27)3833-3668","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (27730818837,"19-03-19","17-08-11","Vivamus@Proineget.co.uk",92,"Ramona","Adria Gilliam","Standart","KVM10GVK1PI","(10)9383-4590","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (32000680826,"19-05-05","19-01-23","Proin@eros.ca",93,"Giacomo","Whoopi Snider","Standart","UOW74PXS9KU","(21)2539-6975","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (46908640442,"17-12-29","18-11-27","velit.egestas@ipsumleoelementum.co.uk",94,"Gabriel","Avram Travis","Standart","PBI28DTB1PH","(23)9009-5444","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (64159437408,"18-10-30","17-07-10","arcu@adipiscingelitCurabitur.net",95,"Lynn","Branden Delaney","Standart","WMK74QTV2RU","(54)2904-4950","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (80578120797,"18-06-20","18-07-22","dignissim.Maecenas.ornare@eratvolutpatNulla.com",96,"Kadeem","Joshua Adkins","Standart","PWI47AFG8SQ","(15)1055-3936","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (66612875973,"18-07-29","19-03-19","malesuada.augue.ut@sedtortor.net",97,"Diana","Jarrod Herman","Standart","JEF53OHU4YI","(94)5779-1865","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (23306941101,"18-05-10","18-05-12","elit@ornareelit.com",98,"Ruby","Regina Dale","Standart","LMK69VKU7HE","(81)9404-3773","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (65730958944,"17-11-09","18-01-03","eget@eu.edu",99,"Cherokee","Jacob Hobbs","Standart","SYQ91MET4OW","(10)2932-5994","1");
INSERT INTO `tb_Cliente` (`cpf`,`data_cadastro`,`data_nascimento`,`email`,`id`,`login`,`nome`,`perfil`,`senha`,`telefone`,`version`) VALUES (91396690811,"18-06-04","19-05-22","leo.elementum@nequeetnunc.com",100,"Donovan","Katelyn Wynn","Standart","RYB54JKW8AM","(26)1474-9168","1");

/*INSERTS PRODUTOS*/
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (64,"libero","id",1,"Dominique","5.70","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (3,"Nulla interdum. Curabitur","ultricies",2,"Erasmus","8.92","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (7,"Integer tincidunt aliquam arcu.","nascetur ridiculus",3,"Anjolie","9.53","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (94,"placerat","Donec fringilla.",4,"Blaze","7.08","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (16,"litora torquent","adipiscing",5,"Farrah","7.12","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (88,"Integer vulputate, risus a","Cum sociis",6,"Reece","2.27","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (15,"tincidunt vehicula","Suspendisse non",7,"Baxteri","2.43","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (30,"egestas. Duis ac","nulla at",8,"Autumn","3.07","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (40,"eros","non enim.",9,"Imelda","7.97","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (56,"purus sapien, gravida","dis parturient",10,"Neil","5.97","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (38,"est, vitae","Aenean sed",11,"Hayes","9.62","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (40,"enim. Etiam gravida","mollis. Duis",12,"Daniel","6.38","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (23,"Phasellus dolor","dolor. Fusce",13,"Oscar","7.74","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (79,"diam luctus lobortis. Class","et magnis",14,"Halla","7.40","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (37,"ante","ut",15,"Chandler","5.20","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (51,"mauris","vestibulum, neque",16,"Yeo","5.60","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (32,"nunc","Praesent",17,"Guy","1.44","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (48,"dapibus","a felis",18,"Hall","3.93","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (84,"Proin nisl","ultrices",19,"Nathan","6.30","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (88,"et netus","arcu. Nunc",20,"Liberty","0.96","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (88,"mauris.","vitae, sodales",21,"Joseph","3.90","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (44,"augue malesuada","Etiam",22,"Lucy","0.27","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (30,"adipiscing elit. Aliquam auctor,","tristique aliquet.",23,"Kirby","1.31","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (9,"habitant morbi","sem,",24,"Noelani","8.71","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (18,"dis","rutrum urna,",25,"Colt","2.66","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (36,"sed dolor.","Quisque",26,"Hector","5.80","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (89,"amet, consectetuer adipiscing elit.","tincidunt",27,"Shaeleigh","8.04","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (4,"nisi. Cum sociis","Nam nulla",28,"Carolyn","3.83","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (40,"tincidunt.","et, lacinia",29,"Sheila","8.60","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (85,"nulla. Donec","at,",30,"Katelyn","5.08","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (14,"tempus mauris","nibh sit",31,"Hop","5.13","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (11,"odio a purus.","ullamcorper viverra.",32,"Wade","6.98","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (49,"mauris.","a",33,"Xena","4.62","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (78,"consectetuer, cursus","Pellentesque ut",34,"Isaiah","6.39","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (21,"sapien molestie orci","Morbi non",35,"Denton","8.11","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (25,"lobortis. Class aptent","purus. Nullam",36,"Stewart","2.57","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (97,"erat nonummy","varius",37,"Shoshana","8.66","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (59,"elit, dictum eu, eleifend","velit dui,",38,"Bruno","4.11","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (36,"Proin ultrices. Duis","elit. Aliquam",39,"Jade","6.01","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (88,"at, iaculis quis,","risus",40,"Bevis","2.98","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (62,"varius","lacinia mattis.",41,"Hedy","1.44","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (100,"Mauris molestie pharetra","arcu.",42,"Britanni","5.24","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (5,"nec","vitae",43,"Tyrone","7.54","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (35,"Aliquam erat volutpat.","lectus",44,"Ian","8.71","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (78,"turpis nec mauris","Aliquam ultrices",45,"Lacey","9.90","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (5,"cursus. Integer","risus",46,"Nichole","7.06","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (87,"Phasellus dolor elit, pellentesque","venenatis",47,"Yoshio","6.30","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (17,"Duis gravida. Praesent eu","vitae,",48,"Colleen","6.56","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (73,"eu tempor erat","urna",49,"Harper","8.28","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (31,"libero at auctor","magna. Suspendisse",50,"Abbot","9.94","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (7,"sollicitudin","et, magna.",51,"Jorden","6.99","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (5,"rutrum, justo. Praesent luctus.","justo. Praesent",52,"Robin","1.63","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (55,"Mauris","purus. Nullam",53,"Lesley","2.14","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (51,"mus.","ligula. Nullam",54,"Quinn","8.88","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (37,"Aliquam fringilla cursus","Integer in",55,"Yuri","5.42","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (29,"non arcu.","sed",56,"Aileen","6.91","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (90,"natoque penatibus","lacus. Etiam",57,"Kameko","8.09","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (6,"blandit congue. In scelerisque","montes,",58,"Julie","8.93","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (39,"non dui nec","velit.",59,"Iliana","2.40","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (66,"sodales elit erat vitae","et arcu",60,"Lenore","3.13","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (24,"ac arcu. Nunc","varius",61,"Ashton","9.47","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (28,"magna et ipsum cursus","netus",62,"Ezekiel","6.82","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (87,"fermentum","risus",63,"Elton","0.96","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (48,"dolor dolor,","arcu",64,"Noble","8.58","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (97,"dapibus","tellus,",65,"Jakeem","7.19","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (9,"Curae;","fames ac",66,"Kelsie","1.92","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (8,"eleifend. Cras sed leo.","ante",67,"Audrey","9.47","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (15,"dis","at,",68,"William","9.56","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (26,"risus quis diam","iaculis enim,",69,"Denise","6.20","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (58,"ornare, facilisis eget, ipsum.","Pellentesque tincidunt",70,"Kevin","6.07","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (17,"vulputate mauris","ornare placerat,",71,"Jaden","4.26","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (65,"velit","sociis",72,"Kylynn","8.44","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (59,"urna.","amet,",73,"Sloane","1.73","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (7,"dui, in sodales elit","sit amet,",74,"Hamish","9.21","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (80,"Cras vulputate","id, mollis",75,"Amena","6.76","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (52,"sagittis augue,","Proin",76,"Ignatius","6.46","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (59,"sed consequat","nibh",77,"Sasha","3.23","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (64,"risus.","vulputate",78,"Kasimir","2.47","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (50,"urna suscipit nonummy.","eget, venenatis",79,"Gannon","3.57","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (36,"arcu. Nunc mauris. Morbi","pellentesque massa",80,"Dahlia","0.69","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (36,"natoque penatibus et","Nullam",81,"Xyla","4.69","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (9,"ultrices","odio semper",82,"Jared","6.93","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (23,"hendrerit id, ante.","accumsan laoreet",83,"August","5.77","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (22,"Praesent interdum ligula eu","Fusce",84,"Callie","5.29","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (78,"Integer aliquam adipiscing","Cras vehicula",85,"Steel","9.76","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (45,"ipsum cursus vestibulum.","ipsum",86,"Trevor","7.75","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (97,"cursus","risus,",87,"Kaye","5.92","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (53,"magna. Lorem","Ut semper",88,"Kendall","1.65","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (43,"Aliquam","mauris",89,"Rebekah","7.70","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (73,"aliquam iaculis, lacus","at,",90,"Connor","2.72","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (65,"a, scelerisque sed, sapien.","nunc. Quisque",91,"Wesley","0.62","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (74,"tristique ac, eleifend","risus varius",92,"Orlando","6.47","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (94,"nunc","Pellentesque",93,"Garrison","6.76","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (45,"nunc.","est,",94,"Kenyon","7.76","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (99,"ipsum. Phasellus vitae mauris","interdum.",95,"Roary","2.00","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (12,"Phasellus vitae","vestibulum,",96,"Baxter","7.62","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (9,"pede,","Nunc",97,"Faith","3.28","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (89,"libero. Proin","dictum mi,",98,"Davis","2.81","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (92,"eget, ipsum. Donec sollicitudin","at",99,"Evelyn","0.82","1");
INSERT INTO `tb_produto` (`id_categoria`,`descricao`,`fabricante`,`id`,`nome`,`preco`,`version`) VALUES (32,"fringilla","fringilla, porttitor",100,"Zelenia","9.24","1");